/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import java.io.File;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import model.Product;

/**
 *
 * @author Likitha G
 */
public class CreateJPanel extends javax.swing.JPanel {

    /**
     * Creates new form CreateJPanel
     */
    
    Product product;
    
    public CreateJPanel(Product product) {
        initComponents();
        this.product = product;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtDOB = new javax.swing.JTextField();
        lblDOB = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        txtUnique = new javax.swing.JTextField();
        txtCertificate = new javax.swing.JTextField();
        lblLinkedin = new javax.swing.JLabel();
        lblSSN = new javax.swing.JLabel();
        txtLinkedin = new javax.swing.JTextField();
        lblCertificate = new javax.swing.JLabel();
        lblMedical = new javax.swing.JLabel();
        lblUnique = new javax.swing.JLabel();
        txtPhone = new javax.swing.JTextField();
        lblDevice = new javax.swing.JLabel();
        txtInternet = new javax.swing.JTextField();
        lblHealth = new javax.swing.JLabel();
        txtBank = new javax.swing.JTextField();
        txtFAX = new javax.swing.JTextField();
        txtVehicle = new javax.swing.JTextField();
        lblPhoto = new javax.swing.JLabel();
        txtAdd1 = new javax.swing.JTextField();
        txtLName = new javax.swing.JTextField();
        txtSSN = new javax.swing.JTextField();
        lblEmail = new javax.swing.JLabel();
        lblPhone = new javax.swing.JLabel();
        txtMedical = new javax.swing.JTextField();
        lblAdd1 = new javax.swing.JLabel();
        lblVehicle = new javax.swing.JLabel();
        lblBank = new javax.swing.JLabel();
        txtHealth = new javax.swing.JTextField();
        lblLName = new javax.swing.JLabel();
        lblInternet = new javax.swing.JLabel();
        lblFAX = new javax.swing.JLabel();
        txtDevice = new javax.swing.JTextField();
        lblCreate = new javax.swing.JLabel();
        btnSave = new javax.swing.JButton();
        lblFName = new javax.swing.JLabel();
        txtFName = new javax.swing.JTextField();
        btnselect = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();

        jPanel1.setBackground(new java.awt.Color(237, 182, 72));

        txtDOB.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        txtDOB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDOBActionPerformed(evt);
            }
        });

        lblDOB.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblDOB.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblDOB.setText("DOB");
        lblDOB.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        txtEmail.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N

        txtUnique.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        txtUnique.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUniqueActionPerformed(evt);
            }
        });

        txtCertificate.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        txtCertificate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCertificateActionPerformed(evt);
            }
        });

        lblLinkedin.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblLinkedin.setText("Linkedln");

        lblSSN.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblSSN.setText("SSN");

        txtLinkedin.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        txtLinkedin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLinkedinActionPerformed(evt);
            }
        });

        lblCertificate.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblCertificate.setText("Certificate/license plates");

        lblMedical.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblMedical.setText("Medical Record Number");

        lblUnique.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblUnique.setText("Unique Identifying Number");

        txtPhone.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        txtPhone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPhoneActionPerformed(evt);
            }
        });

        lblDevice.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblDevice.setText("Device identifiers");

        txtInternet.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        txtInternet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtInternetActionPerformed(evt);
            }
        });

        lblHealth.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblHealth.setText("Health Plan Beneficiary Number");

        txtBank.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        txtBank.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBankActionPerformed(evt);
            }
        });

        txtFAX.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        txtFAX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFAXActionPerformed(evt);
            }
        });

        txtVehicle.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        txtVehicle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtVehicleActionPerformed(evt);
            }
        });

        lblPhoto.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblPhoto.setText("Photo");

        txtAdd1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        txtAdd1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAdd1ActionPerformed(evt);
            }
        });

        txtLName.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        txtLName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLNameActionPerformed(evt);
            }
        });

        txtSSN.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        txtSSN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSSNActionPerformed(evt);
            }
        });

        lblEmail.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblEmail.setText("Email");

        lblPhone.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblPhone.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblPhone.setText("Phone Number");
        lblPhone.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        txtMedical.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        txtMedical.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMedicalActionPerformed(evt);
            }
        });

        lblAdd1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblAdd1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblAdd1.setText("Address");
        lblAdd1.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        lblVehicle.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblVehicle.setText("Vehicle Number");

        lblBank.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblBank.setText("Bank account number");

        txtHealth.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N

        lblLName.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblLName.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblLName.setText("Last Name");

        lblInternet.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblInternet.setText("Internet Protocol Addresses");

        lblFAX.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblFAX.setText("FAX Number");

        txtDevice.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        txtDevice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDeviceActionPerformed(evt);
            }
        });

        lblCreate.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        lblCreate.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCreate.setText("Create Profile");

        btnSave.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        lblFName.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblFName.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblFName.setText("First Name");

        txtFName.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        txtFName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFNameActionPerformed(evt);
            }
        });

        btnselect.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        btnselect.setText("Select Photo");
        btnselect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnselectActionPerformed(evt);
            }
        });

        jTextField1.setBackground(new java.awt.Color(255, 102, 102));
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(btnSave)
                                .addGap(355, 355, 355))
                            .addComponent(lblCreate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblFName, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblDOB, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblFAX, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblPhone)
                            .addComponent(lblEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblSSN, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblLName, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblAdd1, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblMedical, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(79, 79, 79)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtLName, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtFName, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtAdd1, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtDOB, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addComponent(txtPhone, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtFAX, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtEmail, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtSSN, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtMedical, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 110, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblVehicle)
                                    .addComponent(lblLinkedin)
                                    .addComponent(lblInternet)
                                    .addComponent(lblPhoto, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblCertificate)
                                    .addComponent(lblDevice)
                                    .addComponent(lblUnique))
                                .addGap(78, 78, 78)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(txtVehicle, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 131, Short.MAX_VALUE)
                                    .addComponent(txtCertificate, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 131, Short.MAX_VALUE)
                                    .addComponent(txtDevice, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 131, Short.MAX_VALUE)
                                    .addComponent(txtLinkedin, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 131, Short.MAX_VALUE)
                                    .addComponent(txtInternet, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 131, Short.MAX_VALUE)
                                    .addComponent(txtUnique, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 131, Short.MAX_VALUE)
                                    .addComponent(btnselect, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblHealth, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblBank, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(53, 53, 53)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtHealth, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtBank, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addGap(28, 28, 28))
            .addComponent(jTextField1)
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {txtAdd1, txtDOB, txtEmail, txtFAX, txtFName, txtLName, txtMedical, txtPhone, txtSSN});

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {txtCertificate, txtDevice, txtInternet, txtLinkedin, txtUnique, txtVehicle});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblCreate, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblFName)
                            .addComponent(txtFName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(15, 15, 15)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtLName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblLName))
                        .addGap(11, 11, 11)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtAdd1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(lblAdd1, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(11, 11, 11)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtDOB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblDOB, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblFAX)
                            .addComponent(txtFAX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblEmail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtSSN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblSSN, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtMedical, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblMedical))
                        .addGap(75, 75, 75))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblHealth, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtHealth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblBank, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtBank, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(5, 5, 5)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblCertificate, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCertificate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblVehicle, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtVehicle, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblDevice, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtDevice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblLinkedin)
                            .addComponent(txtLinkedin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtInternet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblInternet, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblUnique, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtUnique, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnselect)
                            .addComponent(lblPhoto))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addComponent(btnSave))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(21, 21, 21))))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {txtAdd1, txtDOB, txtEmail, txtFAX, txtFName, txtLName, txtMedical, txtPhone, txtSSN});

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {txtBank, txtCertificate, txtDevice, txtHealth, txtInternet, txtLinkedin, txtUnique, txtVehicle});

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 461, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnselectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnselectActionPerformed
        JFileChooser choosephoto =  new JFileChooser();
        int photo = choosephoto.showOpenDialog(this);
        choosephoto.setCurrentDirectory(new File(System.getProperty("user.home")));
        System.out.println("PHOTO"+photo);
        if(photo == JFileChooser.APPROVE_OPTION) {
            File ChooseFile = choosephoto.getSelectedFile();
            System.out.println("Selected file:" +ChooseFile.getAbsolutePath());
            System.out.println("Selected File Path:" + ChooseFile.getParent());
            jLabel1.setText(ChooseFile.getName());
            product.setPhoto(ChooseFile.getAbsoluteFile().toString());

        }
    }//GEN-LAST:event_btnselectActionPerformed

    private void txtFNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFNameActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:

        String FNameregex = "^[A-Za-z]\\w{1,29}$";
        String Fname = (txtFName.getText());
        if(!Fname.matches(FNameregex) || (Fname.isEmpty())){
            JOptionPane.showMessageDialog(this, "Enter Proper First Name");
        }
        else{
            product.setFName(txtFName.getText());
        }

        String LNameregex = "^[A-Za-z]\\w{1,29}$";
        String Lname = (txtLName.getText());
        if(!Lname.matches(LNameregex) || (Lname.isEmpty())){
            JOptionPane.showMessageDialog(this, "Enter Proper last Name");
        }
        else{
            product.setLName(txtLName.getText());
        }

        String Add1regex = "^[#.0-9a-zA-Z\\s,-]+$";
        String Add1 = (txtAdd1.getText());
        if(!Add1.matches(Add1regex) || (Add1.isEmpty())){
            JOptionPane.showMessageDialog(this, "Enter  Valid Address Line 1");
        }
        else{
            product.setAdd1(txtAdd1.getText());
        }

        String DOBregex = "\\d{2}-\\d{2}-\\d{4}";
        String DOB = (txtDOB.getText());
        if(!DOB.matches(DOBregex) || (DOB.isEmpty())){
            JOptionPane.showMessageDialog(this, "Enter Valid Date of Birth");
        }
        else{
            product.setDOB(txtDOB.getText());
        }

        String Phoneregex = "[0-9]+";
        String Phone = (txtPhone.getText());
        if(!Phone.matches(Phoneregex) || (Phone.isEmpty() || (Phone.length()!=10))){
            JOptionPane.showMessageDialog(this, "Enter Valid Phone Number");
        }
        else{
            product.setPhone(Long.parseLong(txtPhone.getText()));
        }

        String Emailregex = "\\b[\\w.%-]+@[-.\\w]+\\.[A-Za-z]{2,4}\\b";
        String Email = (txtEmail.getText());
        if(!Email.matches(Emailregex) || (Email.isEmpty())){
            JOptionPane.showMessageDialog(this, "Enter Valid Email Number");
        }
        else{
            product.setEmail(txtEmail.getText());
        }

        String FAXregex = "^\\(?(\\d{3})\\)?[- ]?(\\d{3})[- ]?(\\d{4})$";
        String FAX = (txtFAX.getText());
        if(!FAX.matches(FAXregex) || (FAX.isEmpty())){
            JOptionPane.showMessageDialog(this, "Enter Valid FAX Number");
        }
        else{
            product.setFAX(Long.parseLong(txtFAX.getText()));
        }

        String SSNregex = "[0-9]+";
        String SSN = (txtSSN.getText());
        if(!(SSN.matches(SSNregex)) || (SSN.isEmpty() ||  (SSN.length()!=9) )){
            JOptionPane.showMessageDialog(this, "Enter Valid  SSN Number");
        }
        else{
            product.setSSN(Integer.parseInt(txtSSN.getText()));
        }

        String Medicalregex = "[1-9][0-9]{9,14}";
        String Medical = (txtMedical.getText());
        if(!Medical.matches(Medicalregex) || (Medical.isEmpty())){
            JOptionPane.showMessageDialog(this, "Enter Valid Medical Record Number");
        }
        else{
            product.setMedical(Long.parseLong(txtMedical.getText()));
        }

        String Healthregex = "[1-9][0-9]{9,14}";
        String Health = (txtHealth.getText());
        if(!Health.matches(Healthregex) || (Health.isEmpty())){
            JOptionPane.showMessageDialog(this, "Enter Valid Health Plan Beneficiary Number");
        }
        else{
            product.setHealth(Long.parseLong(txtHealth.getText()));
        }

        String Bankregex = "[1-9][0-9]{9,14}";
        String Bank = (txtBank.getText());
        if(!Bank.matches(Bankregex) || (Bank.isEmpty())){
            JOptionPane.showMessageDialog(this, "Enter Valid Bank Account Number");
        }
        else{
            product.setBank(Long.parseLong(txtBank.getText()));
        }

        String Certificateregex = "^[0-9a-zA-Z]{4,15}$";
        String Certificate = (txtCertificate.getText());
        if(!Certificate.matches(Certificateregex) || (Certificate.isEmpty())){
            JOptionPane.showMessageDialog(this, "Enter Valid Certificate/License plates Number");
        }
        else{
            product.setCertificate(txtCertificate.getText());
        }

        String Vehicleregex = "^[0-9a-zA-Z]{4,15}$";
        String Vehicle = (txtVehicle.getText());
        if(!Vehicle.matches(Vehicleregex) || (Vehicle.isEmpty())){
            JOptionPane.showMessageDialog(this, "Enter Valid Vehicle Number");
        }
        else{
            product.setVehicle(txtVehicle.getText());
        }

        String Deviceregex = "^\\d{15}(,\\d{15})*$";
        String Device = (txtDevice.getText());
        if(!Device.matches(Deviceregex) || (Device.isEmpty())){
            JOptionPane.showMessageDialog(this, "Enter Valid Device Number");
        }
        else{
            product.setDevice(txtDevice.getText());
        }

        String Linkedinregex = "^(https?|ftp|file)://[a-zA-Z0-9+&@#/%?=~_|!:,.;]*[a-zA-Z0-9+&@#/%~~_|]";
        String Linkedin = (txtLinkedin.getText());
        if(!Linkedin.matches(Linkedinregex) || (Linkedin.isEmpty())){
            JOptionPane.showMessageDialog(this, "Enter valid LinkedIN ID");
        }
        else{
            product.setLinkedin(txtLinkedin.getText());
        }

        String Internetregex = "\\b(?:[0-9]{1,3}\\.){3}[0-9]{1,3}\\b";
        String Internet = (txtInternet.getText());
        if(!Internet.matches(Internetregex) || (Internet.isEmpty())){
            JOptionPane.showMessageDialog(this, "Enter valid Internet Portal Address");
        }
        else{
            product.setInternet(txtInternet.getText());
        }

        String Uniqueregex = "^\\(?(\\d{3})\\)?[- ]?(\\d{3})[- ]?(\\d{4})$";
        String Unique = (txtUnique.getText());
        if(!Unique.matches(Uniqueregex) || (Unique.isEmpty())){
            JOptionPane.showMessageDialog(this, "Enter valid Unique Identification Number");
        }
        else{
            product.setUnique(txtUnique.getText());
        }
        if(jLabel1.equals("jLabel1")){
                       JOptionPane.showMessageDialog(this, "Upload Photo");
 
        }

        JOptionPane.showMessageDialog(this, "Details saved.");
    }//GEN-LAST:event_btnSaveActionPerformed

    private void txtDeviceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDeviceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDeviceActionPerformed

    private void txtMedicalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMedicalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMedicalActionPerformed

    private void txtSSNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSSNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSSNActionPerformed

    private void txtLNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLNameActionPerformed

    private void txtAdd1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAdd1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAdd1ActionPerformed

    private void txtVehicleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtVehicleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtVehicleActionPerformed

    private void txtFAXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFAXActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFAXActionPerformed

    private void txtBankActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBankActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBankActionPerformed

    private void txtInternetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtInternetActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtInternetActionPerformed

    private void txtPhoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPhoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPhoneActionPerformed

    private void txtLinkedinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLinkedinActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLinkedinActionPerformed

    private void txtCertificateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCertificateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCertificateActionPerformed

    private void txtUniqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUniqueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUniqueActionPerformed

    private void txtDOBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDOBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDOBActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnselect;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel lblAdd1;
    private javax.swing.JLabel lblBank;
    private javax.swing.JLabel lblCertificate;
    private javax.swing.JLabel lblCreate;
    private javax.swing.JLabel lblDOB;
    private javax.swing.JLabel lblDevice;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblFAX;
    private javax.swing.JLabel lblFName;
    private javax.swing.JLabel lblHealth;
    private javax.swing.JLabel lblInternet;
    private javax.swing.JLabel lblLName;
    private javax.swing.JLabel lblLinkedin;
    private javax.swing.JLabel lblMedical;
    private javax.swing.JLabel lblPhone;
    private javax.swing.JLabel lblPhoto;
    private javax.swing.JLabel lblSSN;
    private javax.swing.JLabel lblUnique;
    private javax.swing.JLabel lblVehicle;
    private javax.swing.JTextField txtAdd1;
    private javax.swing.JTextField txtBank;
    private javax.swing.JTextField txtCertificate;
    private javax.swing.JTextField txtDOB;
    private javax.swing.JTextField txtDevice;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtFAX;
    private javax.swing.JTextField txtFName;
    private javax.swing.JTextField txtHealth;
    private javax.swing.JTextField txtInternet;
    private javax.swing.JTextField txtLName;
    private javax.swing.JTextField txtLinkedin;
    private javax.swing.JTextField txtMedical;
    private javax.swing.JTextField txtPhone;
    private javax.swing.JTextField txtSSN;
    private javax.swing.JTextField txtUnique;
    private javax.swing.JTextField txtVehicle;
    // End of variables declaration//GEN-END:variables
}
