/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;


import javax.swing.JOptionPane;
import model.Car;
import model.CarHistory;

/**
 *
 * @author Likitha G
 */
public class CreateJPanel extends javax.swing.JPanel {

   
    CarHistory history;

    public CreateJPanel(CarHistory history) {
        initComponents();
        this.history = history;
    }



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupRadio = new javax.swing.ButtonGroup();
        lblCreate = new javax.swing.JLabel();
        lblOccupy = new javax.swing.JLabel();
        lblBrand = new javax.swing.JLabel();
        lblYear = new javax.swing.JLabel();
        lblSeats = new javax.swing.JLabel();
        lblSerial = new javax.swing.JLabel();
        lblModel = new javax.swing.JLabel();
        lblCertificate = new javax.swing.JLabel();
        txtBrand = new javax.swing.JTextField();
        txtYear = new javax.swing.JTextField();
        txtSeats = new javax.swing.JTextField();
        txtSerial = new javax.swing.JTextField();
        txtModel = new javax.swing.JTextField();
        txtCertificate = new javax.swing.JTextField();
        btnSave = new javax.swing.JButton();
        lblRegister = new javax.swing.JLabel();
        txtRegister = new javax.swing.JTextField();
        chkAvailability = new javax.swing.JCheckBox();
        lblCity = new javax.swing.JLabel();
        txtCity = new javax.swing.JTextField();

        setBackground(new java.awt.Color(153, 153, 153));

        lblCreate.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        lblCreate.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCreate.setText("CREATE CAR DETAILS:");

        lblOccupy.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblOccupy.setText("Occupied");

        lblBrand.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblBrand.setText("Brand");

        lblYear.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblYear.setText("Manufacture Year");

        lblSeats.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblSeats.setText("No of Seats");

        lblSerial.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblSerial.setText("Serial Number");

        lblModel.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblModel.setText("Model Number");

        lblCertificate.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblCertificate.setText("Certificate");

        txtBrand.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBrandActionPerformed(evt);
            }
        });

        txtYear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtYearActionPerformed(evt);
            }
        });

        txtSeats.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSeatsActionPerformed(evt);
            }
        });

        txtModel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtModelActionPerformed(evt);
            }
        });

        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        lblRegister.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblRegister.setText("Registration Date");

        txtRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRegisterActionPerformed(evt);
            }
        });

        chkAvailability.setText("Yes");
        chkAvailability.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkAvailabilityActionPerformed(evt);
            }
        });

        lblCity.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblCity.setText("City");

        txtCity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCityActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(168, 168, 168)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblOccupy)
                                    .addComponent(lblYear)
                                    .addComponent(lblRegister)
                                    .addComponent(lblCity, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(36, 36, 36)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtYear, javax.swing.GroupLayout.DEFAULT_SIZE, 212, Short.MAX_VALUE)
                                    .addComponent(chkAvailability, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtCity)
                                    .addComponent(txtRegister)
                                    .addComponent(txtBrand)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblSeats)
                                    .addComponent(lblSerial)
                                    .addComponent(lblModel)
                                    .addComponent(lblCertificate))
                                .addGap(57, 57, 57)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btnSave)
                                    .addComponent(txtSerial)
                                    .addComponent(txtModel)
                                    .addComponent(txtCertificate)
                                    .addComponent(txtSeats, javax.swing.GroupLayout.DEFAULT_SIZE, 212, Short.MAX_VALUE)))
                            .addComponent(lblBrand)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(lblCreate, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(lblCreate, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRegister)
                    .addComponent(txtRegister, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(chkAvailability)
                    .addComponent(lblOccupy))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBrand)
                    .addComponent(txtBrand, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblYear)
                    .addComponent(txtYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtCity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(lblCity, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSeats)
                    .addComponent(txtSeats, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSerial)
                    .addComponent(txtSerial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblModel)
                    .addComponent(txtModel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCertificate)
                    .addComponent(txtCertificate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addComponent(btnSave)
                .addContainerGap(80, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtBrandActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBrandActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBrandActionPerformed

    private void txtYearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtYearActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtYearActionPerformed

    private void txtSeatsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSeatsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSeatsActionPerformed

    private void txtModelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtModelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtModelActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
      // TODO add your handling code here:  
      Car CAR1 = history.addNewCar();
      
      
      if(txtRegister.getText().isEmpty() || txtBrand.getText().isEmpty() || txtYear.getText().isEmpty() 
              || txtCity.getText().isEmpty() || txtSeats.getText().isEmpty() || txtSerial.getText().isEmpty() 
              || txtModel.getText().isEmpty() || txtCertificate.getText().isEmpty())
      {
          JOptionPane.showMessageDialog(this, "ENTER VALID DETAILS..! ");
          return;
          
      }    
      String registration_date = txtRegister.getText();
      
      String brand = txtBrand.getText();
      int year = Integer.parseInt(txtYear.getText());

      String city = txtCity.getText();
      int seats = Integer.parseInt(txtSeats.getText());
      String serial_number = txtSerial.getText();
       String serialregex = "^[A-Z a-z]{1,5}[0-9]{1,5}$";
        if(!serial_number.matches(serialregex) || (serial_number.isEmpty())){
            JOptionPane.showMessageDialog(this, "Enter Valid Serial Number!");
        }
        else{
            CAR1.setSerial_number(txtSerial.getText());
        }

      
      String model_number = txtModel.getText();
      int certi_year = Integer.parseInt(txtCertificate.getText());
      
      Car CAR = history.addNewCar();
      
      
      CAR.setRegistration_date(registration_date);
      CAR.setBrand(brand);
      CAR.setYear(year);
      CAR.setCity(city);
      CAR.setSeats(seats);
//    CAR.setSerial_number(serial_number);
      CAR.setModel_number(model_number);
      CAR.setCerti_year(certi_year);

        
      JOptionPane.showMessageDialog(this, "New Car Details added!");
      
       if(this.chkAvailability.isSelected()){
           CAR.setOccupied("yes"); 
        }

      txtBrand.setText("");
      txtYear.setText("");
      txtCity.setText("");
      txtSeats.setText("");
      txtSerial.setText("");
      txtModel.setText("");
      txtCertificate.setText("");
      
      
    }//GEN-LAST:event_btnSaveActionPerformed

    private void txtRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRegisterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRegisterActionPerformed

    private void chkAvailabilityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkAvailabilityActionPerformed
        
     
    }//GEN-LAST:event_chkAvailabilityActionPerformed

    private void txtCityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCityActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSave;
    private javax.swing.ButtonGroup buttonGroupRadio;
    private javax.swing.JCheckBox chkAvailability;
    private javax.swing.JLabel lblBrand;
    private javax.swing.JLabel lblCertificate;
    private javax.swing.JLabel lblCity;
    private javax.swing.JLabel lblCreate;
    private javax.swing.JLabel lblModel;
    private javax.swing.JLabel lblOccupy;
    private javax.swing.JLabel lblRegister;
    private javax.swing.JLabel lblSeats;
    private javax.swing.JLabel lblSerial;
    private javax.swing.JLabel lblYear;
    private javax.swing.JTextField txtBrand;
    private javax.swing.JTextField txtCertificate;
    private javax.swing.JTextField txtCity;
    private javax.swing.JTextField txtModel;
    private javax.swing.JTextField txtRegister;
    private javax.swing.JTextField txtSeats;
    private javax.swing.JTextField txtSerial;
    private javax.swing.JTextField txtYear;
    // End of variables declaration//GEN-END:variables
}
