/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Car;
import model.CarHistory;

/**
 *
 * @author Likitha G
 */
public class ViewJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ViewJPanel
     */
    CarHistory history;

    public ViewJPanel(CarHistory history) {
        initComponents();
        this.history = history;

        paneUpdate.setVisible(false);
        paneView.setVisible(false);

        populateTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblView = new javax.swing.JLabel();
        table = new javax.swing.JScrollPane();
        tblCar = new javax.swing.JTable();
        btnDelete = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        paneUpdate = new javax.swing.JPanel();
        lblRegister = new javax.swing.JLabel();
        txtRegister = new javax.swing.JTextField();
        lblOccupy = new javax.swing.JLabel();
        chkAvailability = new javax.swing.JCheckBox();
        lblBrand = new javax.swing.JLabel();
        txtBrand = new javax.swing.JTextField();
        lblYear = new javax.swing.JLabel();
        txtYear = new javax.swing.JTextField();
        lblCity = new javax.swing.JLabel();
        txtCity = new javax.swing.JTextField();
        lblSeats = new javax.swing.JLabel();
        txtSeats = new javax.swing.JTextField();
        lblSerial = new javax.swing.JLabel();
        txtSerial = new javax.swing.JTextField();
        lblModel = new javax.swing.JLabel();
        txtModel = new javax.swing.JTextField();
        btnSubmit = new javax.swing.JButton();
        lblCertificate = new javax.swing.JLabel();
        txtCertificate = new javax.swing.JTextField();
        btnview = new javax.swing.JButton();
        paneView = new javax.swing.JPanel();
        lblRegister2 = new javax.swing.JLabel();
        txtRegister2 = new javax.swing.JTextField();
        lblOccupy2 = new javax.swing.JLabel();
        chkAvailability2 = new javax.swing.JCheckBox();
        lblBrand2 = new javax.swing.JLabel();
        txtBrand2 = new javax.swing.JTextField();
        lblYear2 = new javax.swing.JLabel();
        txtYear2 = new javax.swing.JTextField();
        lblCity2 = new javax.swing.JLabel();
        txtCity2 = new javax.swing.JTextField();
        lblSeats2 = new javax.swing.JLabel();
        txtSeats2 = new javax.swing.JTextField();
        lblSerial2 = new javax.swing.JLabel();
        txtSerial2 = new javax.swing.JTextField();
        lblModel2 = new javax.swing.JLabel();
        txtModel2 = new javax.swing.JTextField();
        lblCertificate2 = new javax.swing.JLabel();
        txtCertificate2 = new javax.swing.JTextField();

        setBackground(new java.awt.Color(153, 153, 153));

        lblView.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        lblView.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblView.setText("VIEW CAR DETAILS:");

        tblCar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Registration Date", "Availability", "Brand", "Manufacturing  Date", "City", "No of Seats", "Serial Number", "Model Number", "Certificate"
            }
        ));
        table.setViewportView(tblCar);

        btnDelete.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnDelete.setText("DELETE");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnUpdate.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        btnUpdate.setText("UPDATE");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        paneUpdate.setBackground(new java.awt.Color(153, 153, 153));

        lblRegister.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblRegister.setText("Registration Date");

        txtRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRegisterActionPerformed(evt);
            }
        });

        lblOccupy.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblOccupy.setText("Occupied");

        chkAvailability.setText("Yes");
        chkAvailability.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkAvailabilityActionPerformed(evt);
            }
        });

        lblBrand.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblBrand.setText("Brand");

        txtBrand.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBrandActionPerformed(evt);
            }
        });

        lblYear.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblYear.setText("Manufacture Year");

        txtYear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtYearActionPerformed(evt);
            }
        });

        lblCity.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblCity.setText("City");

        txtCity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCityActionPerformed(evt);
            }
        });

        lblSeats.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblSeats.setText("No of Seats");

        txtSeats.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSeatsActionPerformed(evt);
            }
        });

        lblSerial.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblSerial.setText("Serial Number");

        lblModel.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblModel.setText("Model Number");

        txtModel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtModelActionPerformed(evt);
            }
        });

        btnSubmit.setText("SUBMIT");
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });

        lblCertificate.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblCertificate.setText("Certificate");

        javax.swing.GroupLayout paneUpdateLayout = new javax.swing.GroupLayout(paneUpdate);
        paneUpdate.setLayout(paneUpdateLayout);
        paneUpdateLayout.setHorizontalGroup(
            paneUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, paneUpdateLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSubmit)
                .addGap(189, 189, 189))
            .addGroup(paneUpdateLayout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(paneUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(paneUpdateLayout.createSequentialGroup()
                        .addGroup(paneUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblOccupy)
                            .addComponent(lblYear)
                            .addComponent(lblRegister)
                            .addComponent(lblCity, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(36, 36, 36)
                        .addGroup(paneUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtYear)
                            .addComponent(chkAvailability, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCity)
                            .addComponent(txtRegister)
                            .addComponent(txtBrand, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(lblBrand)
                    .addGroup(paneUpdateLayout.createSequentialGroup()
                        .addGroup(paneUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblSeats)
                            .addComponent(lblSerial)
                            .addComponent(lblModel)
                            .addComponent(lblCertificate))
                        .addGap(57, 57, 57)
                        .addGroup(paneUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtCertificate)
                            .addComponent(txtSerial)
                            .addComponent(txtModel)
                            .addComponent(txtSeats, javax.swing.GroupLayout.DEFAULT_SIZE, 212, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        paneUpdateLayout.setVerticalGroup(
            paneUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneUpdateLayout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(paneUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRegister)
                    .addComponent(txtRegister, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(paneUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(chkAvailability)
                    .addComponent(lblOccupy))
                .addGap(15, 15, 15)
                .addGroup(paneUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBrand)
                    .addComponent(txtBrand, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(paneUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblYear)
                    .addComponent(txtYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(paneUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtCity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(paneUpdateLayout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(lblCity, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(16, 16, 16)
                .addGroup(paneUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSeats)
                    .addComponent(txtSeats, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(paneUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSerial)
                    .addComponent(txtSerial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(paneUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblModel)
                    .addComponent(txtModel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(paneUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCertificate)
                    .addComponent(txtCertificate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addComponent(btnSubmit)
                .addGap(42, 42, 42))
        );

        btnview.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnview.setText("VIEW");
        btnview.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnviewActionPerformed(evt);
            }
        });

        paneView.setBackground(new java.awt.Color(153, 153, 153));

        lblRegister2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblRegister2.setText("Registration Date");

        txtRegister2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRegister2ActionPerformed(evt);
            }
        });

        lblOccupy2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblOccupy2.setText("Occupied");

        chkAvailability2.setText("Yes");
        chkAvailability2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkAvailability2ActionPerformed(evt);
            }
        });

        lblBrand2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblBrand2.setText("Brand");

        txtBrand2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBrand2ActionPerformed(evt);
            }
        });

        lblYear2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblYear2.setText("Manufacture Year");

        txtYear2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtYear2ActionPerformed(evt);
            }
        });

        lblCity2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblCity2.setText("City");

        txtCity2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCity2ActionPerformed(evt);
            }
        });

        lblSeats2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblSeats2.setText("No of Seats");

        txtSeats2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSeats2ActionPerformed(evt);
            }
        });

        lblSerial2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblSerial2.setText("Serial Number");

        lblModel2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblModel2.setText("Model Number");

        txtModel2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtModel2ActionPerformed(evt);
            }
        });

        lblCertificate2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblCertificate2.setText("Certificate");

        javax.swing.GroupLayout paneViewLayout = new javax.swing.GroupLayout(paneView);
        paneView.setLayout(paneViewLayout);
        paneViewLayout.setHorizontalGroup(
            paneViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 489, Short.MAX_VALUE)
            .addGroup(paneViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(paneViewLayout.createSequentialGroup()
                    .addGap(19, 19, 19)
                    .addGroup(paneViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(paneViewLayout.createSequentialGroup()
                            .addGroup(paneViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblOccupy2)
                                .addComponent(lblYear2)
                                .addComponent(lblRegister2)
                                .addComponent(lblCity2, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(36, 36, 36)
                            .addGroup(paneViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtYear2)
                                .addComponent(chkAvailability2, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtCity2)
                                .addComponent(txtRegister2)
                                .addComponent(txtBrand2, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(paneViewLayout.createSequentialGroup()
                            .addGroup(paneViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblSeats2)
                                .addComponent(lblSerial2)
                                .addComponent(lblModel2)
                                .addComponent(lblCertificate2))
                            .addGap(57, 57, 57)
                            .addGroup(paneViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtSerial2)
                                .addComponent(txtModel2)
                                .addComponent(txtCertificate2)
                                .addComponent(txtSeats2, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addComponent(lblBrand2))
                    .addContainerGap(112, Short.MAX_VALUE)))
        );
        paneViewLayout.setVerticalGroup(
            paneViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 369, Short.MAX_VALUE)
            .addGroup(paneViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(paneViewLayout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(paneViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblRegister2)
                        .addComponent(txtRegister2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(13, 13, 13)
                    .addGroup(paneViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(chkAvailability2)
                        .addComponent(lblOccupy2))
                    .addGap(15, 15, 15)
                    .addGroup(paneViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblBrand2)
                        .addComponent(txtBrand2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(15, 15, 15)
                    .addGroup(paneViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblYear2)
                        .addComponent(txtYear2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(15, 15, 15)
                    .addGroup(paneViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txtCity2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(paneViewLayout.createSequentialGroup()
                            .addGap(1, 1, 1)
                            .addComponent(lblCity2, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGap(16, 16, 16)
                    .addGroup(paneViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblSeats2)
                        .addComponent(txtSeats2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(15, 15, 15)
                    .addGroup(paneViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblSerial2)
                        .addComponent(txtSerial2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(15, 15, 15)
                    .addGroup(paneViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblModel2)
                        .addComponent(txtModel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(15, 15, 15)
                    .addGroup(paneViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblCertificate2)
                        .addComponent(txtCertificate2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(56, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblView, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(table)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnview, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49)
                .addComponent(btnUpdate)
                .addGap(30, 30, 30)
                .addComponent(btnDelete)
                .addGap(62, 62, 62))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(paneUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(paneView, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(80, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblView, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(table, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnUpdate)
                    .addComponent(btnDelete)
                    .addComponent(btnview))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(paneView, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(paneUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(676, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:

        int selectedRowIndex = tblCar.getSelectedRow();

        if (selectedRowIndex < 0) {
            JOptionPane.showMessageDialog(this, "Please select a row to delete.");
            return;
        }

        DefaultTableModel model = (DefaultTableModel) tblCar.getModel();
        Car selectedCar = (Car) model.getValueAt(selectedRowIndex, 0);

        history.deleteCar(selectedCar);

        JOptionPane.showMessageDialog(this, "Car Details Deleted.");

        populateTable();
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:

        int selectedRowIndex = tblCar.getSelectedRow();

        if (selectedRowIndex < 0) {
            JOptionPane.showMessageDialog(this, "Please select a row to Update.");
            return;
        }

        paneView.setVisible(false);
        paneUpdate.setVisible(true);

        DefaultTableModel model = (DefaultTableModel) tblCar.getModel();
        Car selectedCar = (Car) model.getValueAt(selectedRowIndex, 0);

        txtRegister.setText(String.valueOf(selectedCar.getRegistration_date()));
        txtBrand.setText(String.valueOf(selectedCar.getBrand()));
        txtYear.setText(String.valueOf(selectedCar.getYear()));
        txtCity.setText(String.valueOf(selectedCar.getCity()));
        txtSeats.setText(String.valueOf(selectedCar.getSeats()));
        txtSerial.setText(String.valueOf(selectedCar.getSerial_number()));
        txtModel.setText(String.valueOf(selectedCar.getModel_number()));
        txtCertificate.setText(String.valueOf(selectedCar.getCerti_year()));


    }//GEN-LAST:event_btnUpdateActionPerformed

    private void txtRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRegisterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRegisterActionPerformed

    private void chkAvailabilityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkAvailabilityActionPerformed

    }//GEN-LAST:event_chkAvailabilityActionPerformed

    private void txtBrandActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBrandActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBrandActionPerformed

    private void txtYearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtYearActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtYearActionPerformed

    private void txtCityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCityActionPerformed

    private void txtSeatsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSeatsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSeatsActionPerformed

    private void txtModelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtModelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtModelActionPerformed

    private void btnviewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnviewActionPerformed
        // TODO add your handling code here:

        int selectedRowIndex = tblCar.getSelectedRow();

        if (selectedRowIndex < 0) {
            JOptionPane.showMessageDialog(this, "Please select a row to View.");
            return;
        }
        paneUpdate.setVisible(false);
        paneView.setVisible(true);

        DefaultTableModel model = (DefaultTableModel) tblCar.getModel();
        Car selectedCar = (Car) model.getValueAt(selectedRowIndex, 0);

        chkAvailability2.setText(String.valueOf(selectedCar.getOccupied()));
        txtRegister2.setText(String.valueOf(selectedCar.getRegistration_date()));
        txtBrand2.setText(String.valueOf(selectedCar.getBrand()));
        txtYear2.setText(String.valueOf(selectedCar.getYear()));
        txtCity2.setText(String.valueOf(selectedCar.getCity()));
        txtSeats2.setText(String.valueOf(selectedCar.getSeats()));
        txtSerial2.setText(String.valueOf(selectedCar.getSerial_number()));
        txtModel2.setText(String.valueOf(selectedCar.getModel_number()));
        txtCertificate2.setText(String.valueOf(selectedCar.getCerti_year()));

    }//GEN-LAST:event_btnviewActionPerformed

    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed
        // TODO add your handling code here:

        int selectedRowIndex = tblCar.getSelectedRow();
        DefaultTableModel model = (DefaultTableModel) tblCar.getModel();
        Car selectedCar = (Car) model.getValueAt(selectedRowIndex, 0);
        Update(selectedCar);
        paneUpdate.setVisible(false);

    }//GEN-LAST:event_btnSubmitActionPerformed

    private void txtRegister2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRegister2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRegister2ActionPerformed

    private void chkAvailability2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkAvailability2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkAvailability2ActionPerformed

    private void txtBrand2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBrand2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBrand2ActionPerformed

    private void txtYear2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtYear2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtYear2ActionPerformed

    private void txtCity2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCity2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCity2ActionPerformed

    private void txtSeats2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSeats2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSeats2ActionPerformed

    private void txtModel2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtModel2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtModel2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnSubmit;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JButton btnview;
    private javax.swing.JCheckBox chkAvailability;
    private javax.swing.JCheckBox chkAvailability2;
    private javax.swing.JLabel lblBrand;
    private javax.swing.JLabel lblBrand2;
    private javax.swing.JLabel lblCertificate;
    private javax.swing.JLabel lblCertificate2;
    private javax.swing.JLabel lblCity;
    private javax.swing.JLabel lblCity2;
    private javax.swing.JLabel lblModel;
    private javax.swing.JLabel lblModel2;
    private javax.swing.JLabel lblOccupy;
    private javax.swing.JLabel lblOccupy2;
    private javax.swing.JLabel lblRegister;
    private javax.swing.JLabel lblRegister2;
    private javax.swing.JLabel lblSeats;
    private javax.swing.JLabel lblSeats2;
    private javax.swing.JLabel lblSerial;
    private javax.swing.JLabel lblSerial2;
    private javax.swing.JLabel lblView;
    private javax.swing.JLabel lblYear;
    private javax.swing.JLabel lblYear2;
    private javax.swing.JPanel paneUpdate;
    private javax.swing.JPanel paneView;
    private javax.swing.JScrollPane table;
    private javax.swing.JTable tblCar;
    private javax.swing.JTextField txtBrand;
    private javax.swing.JTextField txtBrand2;
    private javax.swing.JTextField txtCertificate;
    private javax.swing.JTextField txtCertificate2;
    private javax.swing.JTextField txtCity;
    private javax.swing.JTextField txtCity2;
    private javax.swing.JTextField txtModel;
    private javax.swing.JTextField txtModel2;
    private javax.swing.JTextField txtRegister;
    private javax.swing.JTextField txtRegister2;
    private javax.swing.JTextField txtSeats;
    private javax.swing.JTextField txtSeats2;
    private javax.swing.JTextField txtSerial;
    private javax.swing.JTextField txtSerial2;
    private javax.swing.JTextField txtYear;
    private javax.swing.JTextField txtYear2;
    // End of variables declaration//GEN-END:variables

    private void Update(Car ch) {
        
        Date currentTime = new Date();
        DateFormat dateFormat = new SimpleDateFormat("dd-MM-yyyy HH:mm:ss");
        String dateTime = dateFormat.format(currentTime);
        ch.setRegistration_date(txtRegister.getText());
        ch.setBrand(txtBrand.getText());
        ch.setYear(Integer.parseInt(txtYear.getText()));
        ch.setSerial_number(txtSerial.getText());
        ch.setSeats(Integer.parseInt(txtSeats.getText()));
        ch.setModel_number(txtModel.getText());
        ch.setCity(txtCity.getText());
        ch.setCerti_year(Integer.parseInt(txtCertificate.getText()));
        ch.setTime(dateTime);
        populateTable();

    }

    private void populateTable() {
        DefaultTableModel model = (DefaultTableModel) tblCar.getModel();

        model.setRowCount(0);
//      System.out.println("size"+ history.getHistory().size());

        for (Car CAR : history.getHistory()) {

            Object[] row = new Object[10];
            row[0] = CAR;
            row[1] = CAR.getOccupied();
            row[2] = CAR.getBrand();
            row[3] = CAR.getYear();
            row[4] = CAR.getCity();
            row[5] = CAR.getSeats();
            row[6] = CAR.getSerial_number();
            row[7] = CAR.getModel_number();
            row[8] = CAR.getCerti_year();

            model.addRow(row);

        }
    }

}
